spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: spring-into
  datasource:
    url: jdbc:mysql://localhost:3306/toll_system?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true

dates:
  weekend: 2
  week: 7
  month: 31
  year: 365

spring-doc:
  api-docs:
    path: /api-docs
spring-doc:
  api-docs:
    path: /api-docs

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
